# Generated by Django 3.2 on 2023-08-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_owner', models.CharField(max_length=200)),
                ('title_fixed', models.CharField(max_length=200)),
                ('title_job', models.CharField(max_length=200)),
            ],
        ),
    ]
