# Generated by Django 3.2 on 2023-08-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('des_title', models.CharField(max_length=230)),
                ('des_title_des', models.TextField()),
                ('des_detail', models.TextField()),
                ('extra_des', models.TextField()),
            ],
        ),
    ]
