# Generated by Django 3.2 on 2023-08-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0002_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('project_des', models.TextField()),
                ('project_owner', models.CharField(max_length=230)),
                ('project_owner_title', models.CharField(max_length=230)),
            ],
        ),
    ]
