# Generated by Django 3.2 on 2023-08-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0005_auto_20230814_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='thumbnailabout',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='home',
            name='thumbnailbio',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
