# Generated by Django 3.2 on 2023-08-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0006_auto_20230814_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_name', models.TextField()),
                ('social_link', models.TextField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
