# Generated by Django 3.2 on 2023-08-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0008_auto_20230814_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='social',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
