# Generated by Django 3.2 on 2023-08-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0009_auto_20230814_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='description',
            field=models.TextField(default=True),
        ),
    ]
