# Generated by Django 3.2 on 2023-08-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0011_alter_resume_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='picowner',
        ),
        migrations.AddField(
            model_name='resume',
            name='ownerimg',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
