# Generated by Django 3.2 on 2023-08-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0012_auto_20230815_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='description',
            field=models.TextField(default='', max_length=255),
        ),
    ]
